"""initial schema

Revision ID: 20260331_0001
Revises: None
Create Date: 2026-03-31 17:00:00
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260331_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "source_configs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("configured", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("sync_mode", sa.String(length=32), nullable=False, server_default="poll"),
        sa.Column("config_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("last_success_at", sa.DateTime(timezone=True)),
        sa.Column("last_failure_at", sa.DateTime(timezone=True)),
        sa.Column("last_error", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_source_configs_source_name", "source_configs", ["source_name"], unique=True)

    op.create_table(
        "source_sync_runs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("sync_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("records_processed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("error_message", sa.Text()),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_source_sync_runs_source_name", "source_sync_runs", ["source_name"], unique=False)
    op.create_index("ix_source_sync_runs_status", "source_sync_runs", ["status"], unique=False)

    table_specs = [
        ("shopify_order_events", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("event_type", sa.String(length=64), nullable=False),
            sa.Column("order_id", sa.String(length=64)),
            sa.Column("event_timestamp", sa.DateTime(timezone=True)),
            sa.Column("business_date", sa.Date()),
            sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("normalized_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
        ("shopify_orders_daily", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("business_date", sa.Date(), nullable=False),
            sa.Column("orders", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("revenue", sa.Float(), nullable=False, server_default="0"),
            sa.Column("average_order_value", sa.Float(), nullable=False, server_default="0"),
            sa.Column("refunds", sa.Float(), nullable=False, server_default="0"),
            sa.Column("source_run_id", sa.Integer(), sa.ForeignKey("source_sync_runs.id")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.UniqueConstraint("business_date", name="uq_shopify_orders_daily_date"),
        ]),
        ("shopify_analytics_intraday", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
            sa.Column("sessions", sa.Float(), nullable=False, server_default="0"),
            sa.Column("users", sa.Float(), nullable=False, server_default="0"),
            sa.Column("conversion_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("revenue", sa.Float(), nullable=False, server_default="0"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
        ("shopify_analytics_daily", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("business_date", sa.Date(), nullable=False),
            sa.Column("sessions", sa.Float(), nullable=False, server_default="0"),
            sa.Column("users", sa.Float(), nullable=False, server_default="0"),
            sa.Column("conversion_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("add_to_cart_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("page_views", sa.Float(), nullable=False, server_default="0"),
            sa.Column("bounce_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.UniqueConstraint("business_date", name="uq_shopify_analytics_daily_date"),
        ]),
        ("tw_summary_intraday", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
            sa.Column("sessions", sa.Float(), nullable=False, server_default="0"),
            sa.Column("users", sa.Float(), nullable=False, server_default="0"),
            sa.Column("conversion_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("add_to_cart_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("purchases", sa.Float(), nullable=False, server_default="0"),
            sa.Column("page_views", sa.Float(), nullable=False, server_default="0"),
            sa.Column("bounce_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("cost_per_session", sa.Float(), nullable=False, server_default="0"),
            sa.Column("cost_per_atc", sa.Float(), nullable=False, server_default="0"),
            sa.Column("revenue", sa.Float(), nullable=False, server_default="0"),
            sa.Column("ad_spend", sa.Float(), nullable=False, server_default="0"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
        ("tw_summary_daily", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("business_date", sa.Date(), nullable=False),
            sa.Column("sessions", sa.Float(), nullable=False, server_default="0"),
            sa.Column("users", sa.Float(), nullable=False, server_default="0"),
            sa.Column("conversion_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("add_to_cart_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("purchases", sa.Float(), nullable=False, server_default="0"),
            sa.Column("page_views", sa.Float(), nullable=False, server_default="0"),
            sa.Column("bounce_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("cost_per_session", sa.Float(), nullable=False, server_default="0"),
            sa.Column("cost_per_atc", sa.Float(), nullable=False, server_default="0"),
            sa.Column("revenue", sa.Float(), nullable=False, server_default="0"),
            sa.Column("ad_spend", sa.Float(), nullable=False, server_default="0"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.UniqueConstraint("business_date", name="uq_tw_summary_daily_date"),
        ]),
        ("tw_metric_catalog", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("metric_id", sa.String(length=128), nullable=False),
            sa.Column("label", sa.String(length=255)),
            sa.Column("category", sa.String(length=128)),
            sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.UniqueConstraint("metric_id", name="uq_tw_metric_catalog_metric_id"),
        ]),
        ("tw_raw_payloads", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("business_date", sa.Date()),
            sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("source_run_id", sa.Integer(), sa.ForeignKey("source_sync_runs.id")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
        ("freshdesk_ticket_events", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("ticket_id", sa.String(length=64), nullable=False),
            sa.Column("event_type", sa.String(length=64), nullable=False),
            sa.Column("event_timestamp", sa.DateTime(timezone=True)),
            sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("normalized_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
        ("freshdesk_tickets", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("ticket_id", sa.String(length=64), nullable=False),
            sa.Column("subject", sa.String(length=500)),
            sa.Column("status", sa.String(length=64)),
            sa.Column("priority", sa.String(length=64)),
            sa.Column("channel", sa.String(length=64)),
            sa.Column("group_name", sa.String(length=128)),
            sa.Column("requester_id", sa.String(length=64)),
            sa.Column("agent_id", sa.String(length=64)),
            sa.Column("created_at_source", sa.DateTime(timezone=True)),
            sa.Column("updated_at_source", sa.DateTime(timezone=True)),
            sa.Column("resolved_at_source", sa.DateTime(timezone=True)),
            sa.Column("first_response_hours", sa.Float()),
            sa.Column("resolution_hours", sa.Float()),
            sa.Column("csat_score", sa.Float()),
            sa.Column("tags_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")),
            sa.Column("category", sa.String(length=128)),
            sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.UniqueConstraint("ticket_id", name="uq_freshdesk_tickets_ticket_id"),
        ]),
        ("freshdesk_tickets_daily", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("business_date", sa.Date(), nullable=False),
            sa.Column("tickets_created", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("tickets_resolved", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("unresolved_tickets", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("reopened_tickets", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("first_response_hours", sa.Float(), nullable=False, server_default="0"),
            sa.Column("resolution_hours", sa.Float(), nullable=False, server_default="0"),
            sa.Column("sla_breach_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("csat", sa.Float(), nullable=False, server_default="0"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.UniqueConstraint("business_date", name="uq_freshdesk_tickets_daily_date"),
        ]),
        ("freshdesk_agent_daily", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("business_date", sa.Date(), nullable=False),
            sa.Column("agent_id", sa.String(length=64), nullable=False),
            sa.Column("agent_name", sa.String(length=128)),
            sa.Column("tickets_resolved", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("first_response_hours", sa.Float(), nullable=False, server_default="0"),
            sa.Column("resolution_hours", sa.Float(), nullable=False, server_default="0"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.UniqueConstraint("business_date", "agent_id", name="uq_freshdesk_agent_daily"),
        ]),
        ("freshdesk_groups_daily", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("business_date", sa.Date(), nullable=False),
            sa.Column("group_name", sa.String(length=128), nullable=False),
            sa.Column("tickets_created", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("tickets_resolved", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("unresolved_tickets", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.UniqueConstraint("business_date", "group_name", name="uq_freshdesk_groups_daily"),
        ]),
        ("kpi_daily", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("business_date", sa.Date(), nullable=False),
            sa.Column("revenue", sa.Float(), nullable=False, server_default="0"),
            sa.Column("orders", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("average_order_value", sa.Float(), nullable=False, server_default="0"),
            sa.Column("sessions", sa.Float(), nullable=False, server_default="0"),
            sa.Column("conversion_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("revenue_per_session", sa.Float(), nullable=False, server_default="0"),
            sa.Column("add_to_cart_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("bounce_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("purchases", sa.Float(), nullable=False, server_default="0"),
            sa.Column("ad_spend", sa.Float(), nullable=False, server_default="0"),
            sa.Column("mer", sa.Float(), nullable=False, server_default="0"),
            sa.Column("cost_per_purchase", sa.Float(), nullable=False, server_default="0"),
            sa.Column("tickets_created", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("tickets_resolved", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("open_backlog", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("first_response_time", sa.Float(), nullable=False, server_default="0"),
            sa.Column("resolution_time", sa.Float(), nullable=False, server_default="0"),
            sa.Column("sla_breach_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("csat", sa.Float(), nullable=False, server_default="0"),
            sa.Column("reopen_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("tickets_per_100_orders", sa.Float(), nullable=False, server_default="0"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.UniqueConstraint("business_date", name="uq_kpi_daily_date"),
        ]),
        ("kpi_intraday", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
            sa.Column("revenue", sa.Float(), nullable=False, server_default="0"),
            sa.Column("orders", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("sessions", sa.Float(), nullable=False, server_default="0"),
            sa.Column("conversion_rate", sa.Float(), nullable=False, server_default="0"),
            sa.Column("average_order_value", sa.Float(), nullable=False, server_default="0"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
        ("driver_diagnostics", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("business_date", sa.Date(), nullable=False),
            sa.Column("diagnostic_type", sa.String(length=64), nullable=False),
            sa.Column("severity", sa.String(length=32), nullable=False),
            sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
            sa.Column("owner_team", sa.String(length=128)),
            sa.Column("title", sa.String(length=255), nullable=False),
            sa.Column("summary", sa.Text(), nullable=False),
            sa.Column("root_cause", sa.Text()),
            sa.Column("details_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
        ("alerts", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("business_date", sa.Date()),
            sa.Column("source", sa.String(length=64), nullable=False),
            sa.Column("severity", sa.String(length=32), nullable=False),
            sa.Column("status", sa.String(length=32), nullable=False, server_default="open"),
            sa.Column("title", sa.String(length=255), nullable=False),
            sa.Column("message", sa.Text(), nullable=False),
            sa.Column("owner_team", sa.String(length=128)),
            sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
            sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
        ("recommendations", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("business_date", sa.Date()),
            sa.Column("owner_team", sa.String(length=128), nullable=False),
            sa.Column("title", sa.String(length=255), nullable=False),
            sa.Column("recommended_action", sa.Text(), nullable=False),
            sa.Column("root_cause", sa.Text()),
            sa.Column("severity", sa.String(length=32), nullable=False),
            sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
            sa.Column("estimated_impact", sa.Text()),
            sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
        ("issue_signals", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("business_date", sa.Date()),
            sa.Column("signal_type", sa.String(length=64), nullable=False),
            sa.Column("severity", sa.String(length=32), nullable=False),
            sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
            sa.Column("source", sa.String(length=64), nullable=False),
            sa.Column("title", sa.String(length=255), nullable=False),
            sa.Column("summary", sa.Text(), nullable=False),
            sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
        ("issue_clusters", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("cluster_key", sa.String(length=128), nullable=False),
            sa.Column("title", sa.String(length=255), nullable=False),
            sa.Column("source_count", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("severity", sa.String(length=32), nullable=False),
            sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
            sa.Column("owner_team", sa.String(length=128)),
            sa.Column("status", sa.String(length=32), nullable=False, server_default="open"),
            sa.Column("details_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.UniqueConstraint("cluster_key", name="uq_issue_clusters_cluster_key"),
        ]),
        ("social_mentions", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("source", sa.String(length=64), nullable=False),
            sa.Column("external_id", sa.String(length=128)),
            sa.Column("url", sa.Text()),
            sa.Column("author", sa.String(length=255)),
            sa.Column("published_at", sa.DateTime(timezone=True)),
            sa.Column("body", sa.Text(), nullable=False),
            sa.Column("sentiment", sa.String(length=32)),
            sa.Column("severity", sa.String(length=32)),
            sa.Column("topic", sa.String(length=128)),
            sa.Column("product", sa.String(length=128)),
            sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
            sa.Column("status", sa.String(length=32), nullable=False, server_default="new"),
            sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
        ("review_mentions", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("source", sa.String(length=64), nullable=False),
            sa.Column("external_id", sa.String(length=128)),
            sa.Column("url", sa.Text()),
            sa.Column("author", sa.String(length=255)),
            sa.Column("published_at", sa.DateTime(timezone=True)),
            sa.Column("rating", sa.Float()),
            sa.Column("body", sa.Text(), nullable=False),
            sa.Column("sentiment", sa.String(length=32)),
            sa.Column("severity", sa.String(length=32)),
            sa.Column("topic", sa.String(length=128)),
            sa.Column("product", sa.String(length=128)),
            sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
            sa.Column("status", sa.String(length=32), nullable=False, server_default="new"),
            sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
        ("community_messages", [
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("source", sa.String(length=64), nullable=False),
            sa.Column("channel", sa.String(length=128)),
            sa.Column("external_id", sa.String(length=128)),
            sa.Column("author", sa.String(length=255)),
            sa.Column("published_at", sa.DateTime(timezone=True)),
            sa.Column("body", sa.Text(), nullable=False),
            sa.Column("sentiment", sa.String(length=32)),
            sa.Column("severity", sa.String(length=32)),
            sa.Column("topic", sa.String(length=128)),
            sa.Column("product", sa.String(length=128)),
            sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
            sa.Column("status", sa.String(length=32), nullable=False, server_default="new"),
            sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]),
    ]

    for table_name, columns in table_specs:
        op.create_table(table_name, *columns)

    indexes = [
        ("ix_shopify_order_events_event_type", "shopify_order_events", ["event_type"]),
        ("ix_shopify_order_events_order_id", "shopify_order_events", ["order_id"]),
        ("ix_shopify_order_events_event_timestamp", "shopify_order_events", ["event_timestamp"]),
        ("ix_shopify_order_events_business_date", "shopify_order_events", ["business_date"]),
        ("ix_shopify_orders_daily_business_date", "shopify_orders_daily", ["business_date"]),
        ("ix_shopify_analytics_intraday_bucket", "shopify_analytics_intraday", ["bucket_start"]),
        ("ix_shopify_analytics_daily_business_date", "shopify_analytics_daily", ["business_date"]),
        ("ix_tw_summary_intraday_bucket", "tw_summary_intraday", ["bucket_start"]),
        ("ix_tw_summary_daily_business_date", "tw_summary_daily", ["business_date"]),
        ("ix_tw_metric_catalog_metric_id", "tw_metric_catalog", ["metric_id"]),
        ("ix_tw_raw_payloads_business_date", "tw_raw_payloads", ["business_date"]),
        ("ix_freshdesk_ticket_events_ticket_id", "freshdesk_ticket_events", ["ticket_id"]),
        ("ix_freshdesk_ticket_events_event_type", "freshdesk_ticket_events", ["event_type"]),
        ("ix_freshdesk_ticket_events_event_timestamp", "freshdesk_ticket_events", ["event_timestamp"]),
        ("ix_freshdesk_tickets_ticket_id", "freshdesk_tickets", ["ticket_id"]),
        ("ix_freshdesk_tickets_status", "freshdesk_tickets", ["status"]),
        ("ix_freshdesk_tickets_priority", "freshdesk_tickets", ["priority"]),
        ("ix_freshdesk_tickets_channel", "freshdesk_tickets", ["channel"]),
        ("ix_freshdesk_tickets_group_name", "freshdesk_tickets", ["group_name"]),
        ("ix_freshdesk_tickets_requester_id", "freshdesk_tickets", ["requester_id"]),
        ("ix_freshdesk_tickets_agent_id", "freshdesk_tickets", ["agent_id"]),
        ("ix_freshdesk_tickets_created_at_source", "freshdesk_tickets", ["created_at_source"]),
        ("ix_freshdesk_tickets_updated_at_source", "freshdesk_tickets", ["updated_at_source"]),
        ("ix_freshdesk_tickets_category", "freshdesk_tickets", ["category"]),
        ("ix_freshdesk_tickets_daily_business_date", "freshdesk_tickets_daily", ["business_date"]),
        ("ix_freshdesk_agent_daily_business_date", "freshdesk_agent_daily", ["business_date"]),
        ("ix_freshdesk_agent_daily_agent_id", "freshdesk_agent_daily", ["agent_id"]),
        ("ix_freshdesk_groups_daily_business_date", "freshdesk_groups_daily", ["business_date"]),
        ("ix_freshdesk_groups_daily_group_name", "freshdesk_groups_daily", ["group_name"]),
        ("ix_kpi_daily_business_date", "kpi_daily", ["business_date"]),
        ("ix_kpi_intraday_bucket", "kpi_intraday", ["bucket_start"]),
        ("ix_driver_diagnostics_business_date", "driver_diagnostics", ["business_date"]),
        ("ix_driver_diagnostics_type", "driver_diagnostics", ["diagnostic_type"]),
        ("ix_driver_diagnostics_severity", "driver_diagnostics", ["severity"]),
        ("ix_driver_diagnostics_owner_team", "driver_diagnostics", ["owner_team"]),
        ("ix_alerts_business_date", "alerts", ["business_date"]),
        ("ix_alerts_source", "alerts", ["source"]),
        ("ix_alerts_severity", "alerts", ["severity"]),
        ("ix_alerts_status", "alerts", ["status"]),
        ("ix_alerts_owner_team", "alerts", ["owner_team"]),
        ("ix_recommendations_business_date", "recommendations", ["business_date"]),
        ("ix_recommendations_owner_team", "recommendations", ["owner_team"]),
        ("ix_recommendations_severity", "recommendations", ["severity"]),
        ("ix_issue_signals_business_date", "issue_signals", ["business_date"]),
        ("ix_issue_signals_signal_type", "issue_signals", ["signal_type"]),
        ("ix_issue_signals_severity", "issue_signals", ["severity"]),
        ("ix_issue_signals_source", "issue_signals", ["source"]),
        ("ix_issue_clusters_cluster_key", "issue_clusters", ["cluster_key"]),
        ("ix_issue_clusters_severity", "issue_clusters", ["severity"]),
        ("ix_issue_clusters_owner_team", "issue_clusters", ["owner_team"]),
        ("ix_social_mentions_source", "social_mentions", ["source"]),
        ("ix_social_mentions_external_id", "social_mentions", ["external_id"]),
        ("ix_social_mentions_published_at", "social_mentions", ["published_at"]),
        ("ix_social_mentions_sentiment", "social_mentions", ["sentiment"]),
        ("ix_social_mentions_severity", "social_mentions", ["severity"]),
        ("ix_social_mentions_topic", "social_mentions", ["topic"]),
        ("ix_social_mentions_product", "social_mentions", ["product"]),
        ("ix_review_mentions_source", "review_mentions", ["source"]),
        ("ix_review_mentions_external_id", "review_mentions", ["external_id"]),
        ("ix_review_mentions_published_at", "review_mentions", ["published_at"]),
        ("ix_review_mentions_sentiment", "review_mentions", ["sentiment"]),
        ("ix_review_mentions_severity", "review_mentions", ["severity"]),
        ("ix_review_mentions_topic", "review_mentions", ["topic"]),
        ("ix_review_mentions_product", "review_mentions", ["product"]),
        ("ix_community_messages_source", "community_messages", ["source"]),
        ("ix_community_messages_channel", "community_messages", ["channel"]),
        ("ix_community_messages_external_id", "community_messages", ["external_id"]),
        ("ix_community_messages_published_at", "community_messages", ["published_at"]),
        ("ix_community_messages_sentiment", "community_messages", ["sentiment"]),
        ("ix_community_messages_severity", "community_messages", ["severity"]),
        ("ix_community_messages_topic", "community_messages", ["topic"]),
        ("ix_community_messages_product", "community_messages", ["product"]),
    ]

    for name, table, cols in indexes:
        op.create_index(name, table, cols, unique=False)


def downgrade() -> None:
    for table in [
        "community_messages",
        "review_mentions",
        "social_mentions",
        "issue_clusters",
        "issue_signals",
        "recommendations",
        "alerts",
        "driver_diagnostics",
        "kpi_intraday",
        "kpi_daily",
        "freshdesk_groups_daily",
        "freshdesk_agent_daily",
        "freshdesk_tickets_daily",
        "freshdesk_tickets",
        "freshdesk_ticket_events",
        "tw_raw_payloads",
        "tw_metric_catalog",
        "tw_summary_daily",
        "tw_summary_intraday",
        "shopify_analytics_daily",
        "shopify_analytics_intraday",
        "shopify_orders_daily",
        "shopify_order_events",
        "source_sync_runs",
        "source_configs",
    ]:
        op.drop_table(table)
