"""Escalation emails for out-of-scope AI assistant requests.

When an employee asks the in-dashboard AI for something that requires
backend code, database changes, or infrastructure work, the AI includes
an [ESCALATE] marker in its response. The SSE handler detects this and
calls send_escalation_email() to notify Joseph so he can act on it.
"""

from __future__ import annotations

import logging
from typing import Optional

import boto3
from botocore.exceptions import BotoCoreError, ClientError

from app.core.config import get_settings

logger = logging.getLogger(__name__)


def send_escalation_email(
    requester_email: str,
    division: str,
    user_message: str,
    escalation_reason: str,
    ai_response_excerpt: str = "",
) -> bool:
    """Send an escalation email to Joseph via SES.

    Returns True if the email was sent successfully.
    """
    settings = get_settings()
    sender = settings.auth_email_from
    recipient = "joseph@spidergrills.com"

    if not sender:
        logger.warning("Escalation email skipped — AUTH_EMAIL_FROM not configured")
        return False

    subject = f"KPI Dashboard: {division} team needs a backend change"

    body_text = (
        f"AI Escalation Request\n"
        f"{'=' * 40}\n\n"
        f"From: {requester_email}\n"
        f"Division: {division}\n\n"
        f"What they asked:\n{user_message}\n\n"
        f"Why it needs you:\n{escalation_reason}\n\n"
    )
    if ai_response_excerpt:
        body_text += f"AI's response to them:\n{ai_response_excerpt[:1000]}\n\n"
    body_text += (
        "---\n"
        "This was auto-generated by the KPI dashboard AI assistant.\n"
        "The employee saw a message explaining their request needs your involvement.\n"
    )

    body_html = (
        '<html><body style="font-family:Arial,sans-serif;color:#111827;line-height:1.6;max-width:560px;margin:0 auto;padding:24px">'
        '<div style="text-align:center;margin-bottom:24px">'
        '<h2 style="margin:0;color:#111827">KPI Dashboard — Escalation</h2>'
        '</div>'
        f'<div style="background:#f0f4ff;border:1px solid #c7d6ff;border-radius:8px;padding:16px;margin-bottom:16px">'
        f'<strong>From:</strong> {requester_email}<br>'
        f'<strong>Division:</strong> {division}'
        f'</div>'
        f'<div style="margin-bottom:16px">'
        f'<strong>What they asked:</strong>'
        f'<div style="background:#f9fafb;border-left:3px solid #4a7aff;padding:12px;margin:8px 0;border-radius:4px">'
        f'{_escape_html(user_message)}'
        f'</div></div>'
        f'<div style="margin-bottom:16px">'
        f'<strong>Why it needs you:</strong>'
        f'<div style="background:#fff7ed;border-left:3px solid #f59e0b;padding:12px;margin:8px 0;border-radius:4px">'
        f'{_escape_html(escalation_reason)}'
        f'</div></div>'
    )
    if ai_response_excerpt:
        body_html += (
            f'<div style="margin-bottom:16px">'
            f'<strong>AI told the employee:</strong>'
            f'<div style="background:#f9fafb;padding:12px;margin:8px 0;border-radius:4px;font-size:13px;color:#374151">'
            f'{_escape_html(ai_response_excerpt[:1000])}'
            f'</div></div>'
        )
    body_html += (
        '<hr style="border:none;border-top:1px solid #e5e7eb;margin:24px 0">'
        '<p style="color:#9ca3af;font-size:12px">Auto-generated by the KPI dashboard AI assistant. '
        'The employee was told their request needs your involvement.</p>'
        '</body></html>'
    )

    try:
        client = boto3.client(
            'sesv2',
            region_name=settings.auth_email_region or settings.aws_region or 'us-east-2',
            aws_access_key_id=settings.aws_access_key_id,
            aws_secret_access_key=settings.aws_secret_access_key,
        )
        client.send_email(
            FromEmailAddress=sender,
            Destination={'ToAddresses': [recipient]},
            Content={
                'Simple': {
                    'Subject': {'Data': subject},
                    'Body': {
                        'Text': {'Data': body_text},
                        'Html': {'Data': body_html},
                    },
                }
            },
        )
        logger.info("Escalation email sent to %s for request from %s", recipient, requester_email)
        return True
    except (ClientError, BotoCoreError) as exc:
        logger.error("Failed to send escalation email: %s", exc)
        return False


def _escape_html(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\n", "<br>")
    )
