import type { KPIDaily, OverviewResponse, SourceHealthItem } from './types'

export const fallbackKpis: KPIDaily[] = [
  {
    business_date: '2026-03-29',
    revenue: 9141.42,
    orders: 16,
    average_order_value: 571.34,
    sessions: 0,
    conversion_rate: 0,
    revenue_per_session: 0,
    add_to_cart_rate: 0,
    bounce_rate: 0,
    purchases: 16,
    ad_spend: 0,
    mer: 0,
    cost_per_purchase: 0,
    tickets_created: 0,
    tickets_resolved: 0,
    open_backlog: 0,
    first_response_time: 0,
    resolution_time: 0,
    sla_breach_rate: 0,
    csat: 0,
    reopen_rate: 0,
    tickets_per_100_orders: 0,
  },
  {
    business_date: '2026-03-30',
    revenue: 18668.38,
    orders: 25,
    average_order_value: 746.74,
    sessions: 9119,
    conversion_rate: 0.614102,
    revenue_per_session: 2.05,
    add_to_cart_rate: 2.160325,
    bounce_rate: 79.460467,
    purchases: 56,
    ad_spend: 605.39,
    mer: 30.84,
    cost_per_purchase: 10.81,
    tickets_created: 0,
    tickets_resolved: 0,
    open_backlog: 0,
    first_response_time: 0,
    resolution_time: 0,
    sla_breach_rate: 0,
    csat: 0,
    reopen_rate: 0,
    tickets_per_100_orders: 0,
  },
  {
    business_date: '2026-03-31',
    revenue: 12296.81,
    orders: 16,
    average_order_value: 768.55,
    sessions: 0,
    conversion_rate: 0,
    revenue_per_session: 0,
    add_to_cart_rate: 0,
    bounce_rate: 0,
    purchases: 16,
    ad_spend: 0,
    mer: 0,
    cost_per_purchase: 0,
    tickets_created: 0,
    tickets_resolved: 0,
    open_backlog: 0,
    first_response_time: 0,
    resolution_time: 0,
    sla_breach_rate: 0,
    csat: 0,
    reopen_rate: 0,
    tickets_per_100_orders: 0,
  },
]

export const fallbackSourceHealth: SourceHealthItem[] = [
  {
    source: 'shopify',
    configured: false,
    enabled: true,
    sync_mode: 'seeded-prototype',
    latest_run_status: 'seeded',
    latest_records_processed: 3,
  },
  {
    source: 'triplewhale',
    configured: false,
    enabled: true,
    sync_mode: 'seeded-prototype',
    latest_run_status: 'seeded',
    latest_records_processed: 1,
  },
  {
    source: 'freshdesk',
    configured: false,
    enabled: true,
    sync_mode: 'poll',
    latest_run_status: 'not-configured',
    latest_records_processed: 0,
  },
]

export const fallbackOverview: OverviewResponse = {
  latest_kpi: fallbackKpis[fallbackKpis.length - 1],
  daily_series: fallbackKpis,
  alerts: [
    {
      id: 1,
      source: 'prototype',
      severity: 'high',
      status: 'open',
      title: 'Revenue decline detected',
      message: 'Revenue dropped sharply versus the previous day and should be investigated.',
      owner_team: 'Growth / UX',
      confidence: 0.82,
      metadata_json: {},
    },
  ],
  diagnostics: [
    {
      id: 1,
      business_date: '2026-03-31',
      diagnostic_type: 'revenue_drop',
      severity: 'high',
      confidence: 0.82,
      owner_team: 'Growth / UX',
      title: 'Revenue down',
      summary: 'Revenue appears to be under pressure and conversion/PDP quality should be reviewed first.',
      root_cause: 'conversion_down',
      details_json: {},
    },
  ],
  recommendations: [
    {
      id: 1,
      business_date: '2026-03-31',
      owner_team: 'Growth / UX',
      title: 'Priority action',
      recommended_action: 'Investigate checkout friction, PDP clarity, pricing presentation, and trust signals.',
      root_cause: 'conversion_down',
      severity: 'high',
      confidence: 0.82,
      estimated_impact: 'High revenue preservation and conversion recovery potential.',
    },
  ],
  source_health: fallbackSourceHealth,
}
